export const ASIGNATURAS_PROYECTO = "ASIGNATURAS_PROYECTO";
export const CREAR_ASIGNATURA = "CREAR_ASIGNATURA";
export const ELIMINAR_ASIGNATURA = "ELIMINAR_ASIGNATURA";
export const MODIFICAR_ASIGNATURA = "MODIFICAR_ASIGNATURA";

export const ALUMNOS_PROYECTO = "ALUMNOS_PROYECTO";
export const CREAR_ALUMNO = "CREAR_ALUMNO";
export const ELIMINAR_ALUMNO = "ELIMINAR_ALUMNO";
export const MODIFICAR_ALUMNO = "MODIFICAR_ALUMNO";

export const NOTAS_PROYECTO = "NOTAS_PROYECTO";
export const CREAR_NOTA = "CREAR_NOTA";
export const ELIMINAR_NOTA = "ELIMINAR_NOTA";
export const MODIFICAR_NOTA = "MODIFICAR_NOTA";
